spring.application.name=order-service

#mongo properties
spring.data.mongodb.uri:mongodb://localhost:27017/order_db
spring.data.mongodb.auto-index-creation=true

#JWT properties
jwt.secret=mysecretkeymysecretkeymysecretkey123456
jwt.expiration=86400000